# 一、ndarray
## 1. ndarray的特性
### 多维性

In [23]:
import numpy as np

In [24]:
arr = np.array(5) # 0维ndarray数组
print(arr)
print('arr的维度:', arr.ndim)

5
arr的维度: 0


In [25]:
arr = np.array([1, 2, 3]) # 1维ndarray数组
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3]
arr的维度: 1


In [26]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]]) # 0维ndarray数组
print(arr)
print('arr的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


# 同质性

In [27]:
arr = np.array([1, 'hello'])  # 数据类型不同的强制转换
print(arr)

['1' 'hello']


In [28]:
arr = np.array([1, 2.5]) # 强制转换为相同类型的数据
print(arr)

[1.  2.5]


# 2. ndarray的属性

In [29]:
arr0 = np.array(1)
arr1 = np.array([1, 2.5, 3])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(arr0)
print(f'0维数组的形状: {arr0.shape} 维数: {arr0.ndim}  个数：{arr0.size} 数据类型{arr0.dtype}')
print(f'1维数组的形状: {arr1.shape} 维数: {arr1.ndim}  个数：{arr1.size} 数据类型{arr1.dtype}')
print(f'2维数组的形状: {arr2.shape} 维数: {arr2.ndim}  个数：{arr2.size} 数据类型{arr2.dtype}')

arr4 = arr2.T
print(f'0维数组的形状: {arr4.shape} 维数: {arr4.ndim}  个数：{arr4.size} 数据类型{arr4.dtype}')


1
0维数组的形状: () 维数: 0  个数：1 数据类型int32
1维数组的形状: (3,) 维数: 1  个数：3 数据类型float64
2维数组的形状: (2, 3) 维数: 2  个数：6 数据类型int32
0维数组的形状: (3, 2) 维数: 2  个数：6 数据类型int32


# 3. ndarray的创建

In [30]:
# 基础创建方法
list = [1, 2, 3]
arr = np.array(list, dtype=np.float64) # 前面本质就是传一个python的list
print(arr.ndim, arr.dtype) # 属性


1 float64


In [31]:
# copy()
arr1 = np.copy(arr) # 深拷贝
print(arr1)

[1. 2. 3.]


In [32]:
# 自定义形状
# 全0 全1 未初始化 固定值

# 1. 全0
arr = np.zeros((2, 3), dtype=int) # 默认float64，可以手动指定
# print(arr)

# 2. 全1
arr = np.ones((2, 3), dtype=int) # 默认float64，可以手动指定
# print(arr)

# 3. 未初始化
arr = np.empty((4, 3)) # 内存里是什么就显示什么
# print(arr)

# 4. 固定值
arr = np.full((3, 4), 2026)
print(arr)

# 5. _like形状
arr = np.zeros_like(arr)
# print(arr)
arr = np.ones_like(arr)
# print(arr)
arr = np.empty_like(arr)
# print(arr)
arr = np.full_like(arr, 2)
print(arr)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [33]:
# 指定步长取
arr = np.arange(1, 10, 2) # 左闭右开
print(arr)
# 指定个数取(线性)
arr = np.linspace(0, 4, 2, dtype=int) # 闭区间
print(arr)
# 指定个数取（log)
arr = np.logspace(0, 4, 2, base=2, dtype=int) # 闭区间，等间隔取完，然后取指数函数
print(arr)

[1 3 5 7 9]
[0 4]
[ 1 16]


# 4. 特殊矩阵

In [34]:
# 单位阵
arr = np.eye(3, 4, dtype=int) # 行列分开传就行，不要传入元组
print(arr)
# 对角阵
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# 5. 随机数组

In [35]:
np.random.seed(42) # 随机数种子

# 随机整数
arr = np.random.randint(3, 6, (2, 3))
print(arr)

# 0, 1之间的随机浮点数（均匀分布）
arr = np.random.rand(3, 4)
print(arr)
# 别的范围区间
arr = np.random.uniform(3, 6, (2, 3))
print(arr)

# 正态分布
arr = np.random.randn(2, 3)
print(arr)

[[5 3 5]
 [5 3 3]]
[[0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]
[[3.91272673 4.57426929 4.29583506]
 [3.87368742 4.83555868 3.41848158]]
[[-0.90802408 -1.4123037   1.46564877]
 [-0.2257763   0.0675282  -1.42474819]]


# 6. 数据类型

In [36]:
arr = np.array([1, 2, 3], dtype=bool)
print(arr)

[ True  True  True]


# 7. 索引与切片


In [37]:
# 一维数组
np.random.seed(42)
arr = np.random.randint(1, 100, 20)
print(arr)
print(arr[10])
print(arr[:])

print(arr[2: 5]) # 切片左闭右开
print(arr[slice(2, 15, 3)]) # 切片函数，等价的，所以用上面的就行

# 用bool索引取数据
print(arr[arr>10]) # 选元素大于10的，arr>10返回bool数组
print(arr[(arr>10) & (arr<70)]) # 选元素>10且<70，arr>10返回bool数组
print('-' * 50)


# 二维数组
arr = np.random.randint(1, 100, (4, 8))
print(arr)
print(arr[1, 3]) # 索引
print(arr[1, 2:5]) # 切片

print(arr[arr>50]) # 返回1维数组，与几维没关系

# 找第2行、元素大于50的。先取第2行，再bool索引找
print(arr[2][arr[2]>50])
# 找第3列、元素>50的
print(arr[:, 3][arr[:, 3]>50])

[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]
88
[52 93 15 72 61 21 83 87 75 75 88 24  3 22 53  2 88 30 38  2]
[15 72 61]
[15 21 75 24 53]
[52 93 15 72 61 21 83 87 75 75 88 24 22 53 88 30 38]
[52 15 61 21 24 22 53 30 38]
--------------------------------------------------
[[64 60 21 33 76 58 22 89]
 [49 91 59 42 92 60 80 15]
 [62 62 47 62 51 55 64  3]
 [51  7 21 73 39 18  4 89]]
42
[59 42 92]
[64 60 76 58 89 91 59 92 60 80 62 62 62 51 55 64 51 73 89]
[62 62 62 51 55 64]
[62 73]


# 8. ndarray的数学二元运算

In [38]:
# 算数运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b) # numpy重写了+法，python原生语法中，是字符串的拼接，如果python要实现这个，要写一个for循环
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)

print(a + 3) # 数组与标量相加，则利用广播机制运算

# 广播机制
# 先广播再运算，当然要能广播才行，广播的条件是：从后往前数，维度相同或者其中一个为1
a = np.array([1, 2, 3])
b = np.array([[4], [5], [6]])
print(a + b)

# 矩阵运算
a = np.random.randint(1, 10, (3, 4))
b = np.random.randint(1, 10, (4, 3))
print(a @ b) # numpy重写了@运算符


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[4 5 6]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 88  64 104]
 [ 98  73 125]
 [ 96  78 110]]


# 9. ndarray的数学函数

In [39]:
# 平方根
arr = np.logspace(0, 4, 5, base=2, dtype=int)
arr = np.sqrt(arr)
print(arr)

# 计算指数
a = np.array([1, 2, 3])
print(np.exp(a))
print(np.power(2, a)) # 以2为底的指数函数

# 计算对数
a = np.array([1, 2, 3])
print(np.log(a)) # 以e为底的对数
# 内置log2、log10，如果是其他底，只能用换底公式
print(np.log(a) / np.log(3))

# 三角函数
print(np.sin(a), np.cos(np.pi))

# 绝对值
print(np.abs(a))

# 取整
print(np.round([1.2, 1.5, 1.7]))
# 向上取整、向下取整
print(np.ceil([1.2, 1.5, 1.7]))
print(np.floor([1.2, 1.5, 1.7]))

# 检测缺失值
print(np.isnan([1, 2, np.nan, 4]))
print(np.isinf([1, 2, np.inf, 4]))


[1.         1.41421356 2.         2.82842712 4.        ]
[ 2.71828183  7.3890561  20.08553692]
[2 4 8]
[0.         0.69314718 1.09861229]
[0.         0.63092975 1.        ]
[0.84147098 0.90929743 0.14112001] -1.0
[1 2 3]
[1. 2. 2.]
[2. 2. 2.]
[1. 1. 1.]
[False False  True False]
[False False  True False]


# 10. ndarray的统计函数

In [40]:
np.random.seed(42)
arr = np.random.randint(1, 100, 8)
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))

print(np.var(arr))
print(np.std(a))

print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr))
print(np.argmin(arr))

# 分位数，中位数是特殊的分位数
print(np.percentile(arr, 50))

# 累计和、累计积
print(np.cumsum(arr))
print(np.cumprod(arr))

[52 93 15 72 61 21 83 87]
484
60.5
66.5
762.5
0.816496580927726
93
15
1
2
66.5
[ 52 145 160 232 293 314 397 484]
[         52        4836       72540     5222880   318595680 -1899425312
  1261489056 -1919601824]


# 11. 比较函数

In [41]:
np.random.seed(42)
arr1 = np.random.rand(2, 3)
arr2 = np.random.randn(2, 3)
print(arr1)
print(arr2)

# 是否大于
list = [2, 3, 4, 5]
print(np.greater(list, 4))
print(np.less(list, 4))
print(np.equal(list, 4))
print("-" * 50)

# 逻辑运算
print(np.equal(arr1, arr2))
print(np.logical_and([0, 0], [1, 1])) # 逻辑与
print(np.logical_or([0, 0], [1, 1]))
print(np.logical_not([0, 1, 0]))

# 检查一个array是否有一个为true
print(np.any([1, 2, 3, 0]))
# 检查元素是否都是true
print(np.all([1, 2, 3, 0]))

# 自定义条件
print(np.where(arr>1, arr, 0))
# 可以用来分类
score = np.random.randint(0, 100, 20)
print(np.where(score>=60, '及格', '不及格'))
# 如果是多分类，就嵌套
print(np.where(score<60, '不及格',
               np.where(score<80, '良好', '优秀'))) # 就是python里的if elif
# 另一种多分类方法
print(np.select([score>=80, (score<80) & (score>=60), score<60], ['优秀', '良好', '不及格'], default='未知'))

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
[[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]
[False False False  True]
[ True  True False False]
[False False  True False]
--------------------------------------------------
[[False False False]
 [False False False]]
[False False]
[ True  True]
[ True False  True]
True
False
[52 93 15 72 61 21 83 87]
['及格' '不及格' '不及格' '及格' '不及格' '及格' '不及格' '不及格' '及格' '不及格' '及格' '不及格' '及格'
 '及格' '不及格' '及格' '不及格' '不及格' '及格' '不及格']
['良好' '不及格' '不及格' '优秀' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格' '良好' '不及格' '良好'
 '良好' '不及格' '良好' '不及格' '不及格' '良好' '不及格']
['良好' '不及格' '不及格' '优秀' '不及格' '优秀' '不及格' '不及格' '优秀' '不及格' '良好' '不及格' '良好'
 '良好' '不及格' '良好' '不及格' '不及格' '良好' '不及格']


# 12. ndarray的排序函数

In [44]:
np.random.seed(8)
arr = np.random.randint(1, 100, 20)

# python内置的sort方法原地修改，而且返回none，因此要返回修改后的，直接引用原来的名字就行
print(arr)
print(arr.sort())
print(arr)

# np.sort()不会原位修改，而且函数返回修改后的
print(np.sort(arr))
# 如果要倒序，只能用切片
print(np.sort(arr)[::-1])

arr1 = np.array([[3, 2, 1],
                 [2, 1, 3]])

 # axis=1不同列之间排序，axis=0不同行之间排序，默认axis=0
print(np.sort(arr1, axis=1))

print(np.argsort(arr)) # 不修改array，但是返回索引值


[68 85  6 91  9 84 64 49 86 61 50 75 28 14 10 62 16 94 99 60]
None
[ 6  9 10 14 16 28 49 50 60 61 62 64 68 75 84 85 86 91 94 99]
[ 6  9 10 14 16 28 49 50 60 61 62 64 68 75 84 85 86 91 94 99]
[99 94 91 86 85 84 75 68 64 62 61 60 50 49 28 16 14 10  9  6]
[[1 2 3]
 [1 2 3]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# 13. 其他函数

In [45]:
arr = np.random.randint(1, 20, 30)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr)

# 去重
print(np.unique(arr)) # 去重并重排

# 拼接
arr1 = np.reshape(arr1, (1, 3))
arr2 = np.reshape(arr2, (1, 3))
print(np.concatenate((arr1, arr2), axis=1)) # 必须传入元组或列表才能拼接
print(np.concatenate((arr1, arr2), axis=0))

# 分割
print(np.split(arr, 5)) # 必须等分才行，否则报错
print(np.split(arr, (1, 6, 18))) # 在指定位置分割，剩下的单独一个

# 调整形状
print(np.reshape(arr, (3, 10)))

# 上面函数的参数中，列表或元组都行


[19 15  7 10  5  8 11 10  3  7 10  6 15 18 12 16 12 14  9 16 11  1  8 14
  3  7  8  5  7  5]
[ 1  3  5  6  7  8  9 10 11 12 14 15 16 18 19]
[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[array([19, 15,  7, 10,  5,  8]), array([11, 10,  3,  7, 10,  6]), array([15, 18, 12, 16, 12, 14]), array([ 9, 16, 11,  1,  8, 14]), array([3, 7, 8, 5, 7, 5])]
[array([19]), array([15,  7, 10,  5,  8]), array([11, 10,  3,  7, 10,  6, 15, 18, 12, 16, 12, 14]), array([ 9, 16, 11,  1,  8, 14,  3,  7,  8,  5,  7,  5])]
[[19 15  7 10  5  8 11 10  3  7]
 [10  6 15 18 12 16 12 14  9 16]
 [11  1  8 14  3  7  8  5  7  5]]
