In [1]:
# 1. 温度数据分析
## 某城市一周的最高气温为 [28, 30, 29, 31, 32, 30, 29]
### 计算平均气温、最高气温、最低气温
### 找出气温超过30度的天数
import numpy as np
temps = np.array([28, 30, 29, 31, 32, 30, 29])
print(temps)
print(f'{np.mean(temps):.2f}')
print(np.max(temps))
print(np.min(temps))

print(f'气温超过30的天数：{len(temps[temps>30])}')
# 方法很多
print(f'气温超过30的天数：{np.sum(np.where(temps>30, 1, 0))}')

[28 30 29 31 32 30 29]
29.86
32
28
气温超过30的天数：2
气温超过30的天数：2


In [2]:
# 2. 学生成绩统计
# 某班级5名学生的数学成绩为 [85, 90, 78, 92, 88]
# ● 计算成绩的平均分、中位数、标准差
# ● 将成绩从百分制转换为十分制
score = np.array([85, 90, 78, 92, 88])
print(np.mean(score), np.median(score), np.std(score))
print(score / 10)

86.6 88.0 4.882622246293481
[8.5 9.  7.8 9.2 8.8]


In [3]:
# 3. 矩阵乘法
# 计算A + B和A * B
# 计算A和B的乘法
A = np.array([[1, 2],
     [3, 4]])
B = np.array([[5, 6],
     [7, 8]])
print(A + B)
print(A * B)
print(A @ B)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [5]:
# 4. 随机数据生成
# 生成一个 3x4 的随机整数数组，范围 [0, 10)
# ● 计算每列的最大值和每行的最小值
# ● 将数组中的所有奇数替换为-1
np.random.seed(42)
arr = np.random.randint(0, 10, [3, 4])
print(arr)
print(np.max(arr, axis=1))
print(np.max(arr, axis=0))
print(np.where(arr % 2 == 1, -1, arr)) # 并不修改array

# 法2：bool索引法
arr[arr%2==1] = -1 # 这样直接修改了array
print(arr)

arr[arr%2==1] # 注意，这样返回列表，但是上面可以取索引再赋值，很神奇。但是要


[[6 3 7 4]
 [6 9 2 6]
 [7 4 3 7]]
[7 9 7]
[7 9 7 7]
[[ 6 -1 -1  4]
 [ 6 -1  2  6]
 [-1  4 -1 -1]]
[[ 6 -1 -1  4]
 [ 6 -1  2  6]
 [-1  4 -1 -1]]


array([-1, -1, -1, -1, -1, -1])

In [ ]:
# 5. 数组变形
# 创建一个1到12的一维数组，并转换为 3x4的二维数组
# ● 计算每行的和、每列的平均值
# ● 将数组展平为一维数组
arr = np.arange(1, 13, 1)
print(arr)
arr_re = np.reshape(arr, (3, 4))
print(arr_re)
print(np.sum(arr_re, axis=1))
print(np.mean(arr_re, axis=0))
print(np.reshape(arr_re, 12))
# 或
print(arr_re.flatten()) # 方法



[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# 6. 布尔索引
# 生成一个 5x5 的随机数组，范围 [0, 20)
# ● 找出数组中大于10的元素
# ● 将所有大于10的元素替换为0
arr = np.random.uniform(0, 20, [5, 5])
print(arr[arr>10])
arr[arr>10] = 0 # 注意，这样是原地修改
print(arr)

[13.37682505 13.31844713 11.82595575 11.22486852 19.43424191 16.97827649
 14.43459042 14.21325779 17.91527191 11.26551144 13.91032173 12.08834759
 10.79682183]
[[1.90820233 7.41636504 0.         0.         0.        ]
 [5.49443586 0.         7.6585375  0.         0.        ]
 [0.         4.71969839 5.12136646 0.80867179 0.        ]
 [2.21781642 8.78673004 4.03438405 0.         9.50740446]
 [0.         0.         2.78662909 0.         0.        ]]


In [ ]:
# 7. 统计函数应用
# 某公司6个月的销售鹅（万元）为[120, 135, 110, 125, 130, 140]
# ● 计算销售额的总和、均值、方差
# ● 找出销售额最高的月份和最低的月份
arr = np.array([120, 135, 110, 125, 130, 140])
print(np.sum(arr))
print(np.mean(arr))
print(np.var(arr))
print(np.argmax(arr) + 1)
print(np.argmin(arr) + 1)

760
126.66666666666667
97.22222222222223
5
2


In [ ]:
# 8. 数组拼接
# 给定 A = [1,2,3] 和 B = [4,5,6]。
# ● 将A和B水平拼接为一个新数组
# ● 将A和B垂直拼接为一个新数组
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(np.concatenate([A, B]))
print(np.concatenate([np.reshape(A, (1, 3)), np.reshape(B, [1, 3])]))
print('-' * 50)
# 或(推荐)
print(np.hstack([A, B]))
print(np.vstack([A, B]))
# 或
print(np.reshape(np.concatenate((A, B)),[2, 3]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
--------------------------------------------------
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:
# 9. 唯一值与排序
# 给定数组[2,1,2,3,1,4,3]
# ● 找出数组中的唯一值并排序
# ● 计算每个唯一值出现的次数
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))
uni_arr, counts = np.unique(arr, return_counts=True) # 想要返回计数，设置参数就行
print(counts)

[1 2 3 4]
[2 2 2 1]


In [ ]:
# # 10. 
# 销售额 [20, 25, 22, 30, 28]
# 成本   [15, 18, 16, 22, 20]
# 计算每天的利润
# 计算利润的平均值与方差
# 找出利润最高的天数
sales = np.array([20, 25, 22, 30, 28])
cost = np.array([15, 18, 16, 22, 20])
profit = sales - cost
print(np.mean(profit))
print(np.var(profit))
print(np.sum(profit==np.max(profit)))

# 注意
print(np.argmax(profit)) # 只返回一个结果

6.8
1.3599999999999999
2
